openapi: 3.0.3
info:
  title: Local File Storage API
  version: 1.0.0
  description: API for uploading and retrieving image files from local storage
servers:
  - url: http://localhost:8081
paths:
#TODO: FILE
  /api/v1/auth/account:
    get:
      tags:
        - Authentication & Authorization
      summary: Test to get all Accounts
      responses:
        '200':
          description: Get accounts successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  filename:
                    type: string
        '500':
          description: Internal Server Error
  /api/v1/auth/login:
    post:
      tags:
        - Authentication & Authorization
      summary: Login
      description: Authenticates a user with email and password. Returns an access token in the response body and sets a refresh token as an HttpOnly cookie.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          headers:
            Set-Cookie:
              description: Refresh token cookie
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    nullable: true
                  message:
                    type: object
                  code:
                    type: integer
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    nullable: true
                  message:
                    type: string
                  code:
                    type: integer
        '500':
          description: Internal Server Error
  /api/v1/auth/register:
    post:
      tags:
        - Authentication & Authorization
      summary: Register
      description: Register a new user account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    nullable: true
                  message:
                    type: object
                  code:
                    type: integer
        '500':
          description: Internal Server Error
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    LoginResponse:
      type: object
      properties:
        access_token:
          type: string
        expires_at:
          type: integer
          format: int64
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
        - role_id
    RegisterResponse:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        is_active:
          type: boolean
        role_id:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
